class HighRackEntity {
  DataEntity? data;
  int? code;
  bool? succeeded;
  String? message;
  String? description;

  HighRackEntity({
    required this.data,
    required this.code,
    required this.succeeded,
    required this.message,
    required this.description,
  });

  factory HighRackEntity.fromJson(Map<String, dynamic> json) => HighRackEntity(
        data: json["Data"] != null ? DataEntity.fromJson(json["Data"]) : null,
        code: json["Code"],
        succeeded: json["Succeeded"],
        message: json["Message"],
        description: json["Description"],
      );
}

class DataEntity {
  String? id;
  String? containerType;
  String? idCompany;
  String? shipName;
  String? shipDeparture;
  String? containerNumber;
  String? fzNumberComplete;
  String? fzNumber;
  String? consigneeName;
  String? size;
  String? summaryPallet;
  String? voyageNumber;
  String? country;
  String? architecture;
  String? taraWeight;
  String? sealNumber;
  String? consigneeNumber;
  String? packageId;
  String? fzNoVolume;
  String? fzSummaryVolume;
  String? packageWeight;
  String? summaryPalettWeight;
  int? quantityFz;
  int? quantityPalett;
  int? quantityFzPalett;
  String? commissionNumberFrom;
  String? commissionNumberTo;
  String? packageDescription1;
  String? modelType;
  String? lot;
  String? packageLength;
  String? packageWidth;
  String? packageHeight;
  String? paletteFz;
  String? packageDescription2;
  String? partNoPrintFormat;
  String? partNoReadFormat;
  String? es1;
  String? es2;
  int? quantity;
  String? indexNo;
  String? descriptionGerman;
  String? desciptonEnglish;
  String? partWeight;
  String? assistantPackingMaterial;
  String? packer;
  String? hsCode;
  String? preferentialOrigin;
  String? createBy;
  String? createDate;
  String? filename;
  String? packingMonth;
  String? buildingName;
  String? areaName;
  String? sectionId;
  String? sectionCode;
  String? sectionName;
  String? idLocationRack;
  String? area;
  String? codeRack;
  String? rackName;
  String? unpackBy;
  String? unpackDate;

  DataEntity({
    required this.id,
    required this.containerType,
    required this.idCompany,
    required this.shipName,
    required this.shipDeparture,
    required this.containerNumber,
    required this.fzNumberComplete,
    required this.fzNumber,
    required this.consigneeName,
    required this.size,
    required this.summaryPallet,
    required this.voyageNumber,
    required this.country,
    required this.architecture,
    required this.taraWeight,
    required this.sealNumber,
    required this.consigneeNumber,
    required this.packageId,
    required this.fzNoVolume,
    required this.fzSummaryVolume,
    required this.packageWeight,
    required this.summaryPalettWeight,
    required this.quantityFz,
    required this.quantityPalett,
    required this.quantityFzPalett,
    required this.commissionNumberFrom,
    required this.commissionNumberTo,
    required this.packageDescription1,
    required this.modelType,
    required this.lot,
    required this.packageLength,
    required this.packageWidth,
    required this.packageHeight,
    required this.paletteFz,
    required this.packageDescription2,
    required this.partNoPrintFormat,
    required this.partNoReadFormat,
    required this.es1,
    required this.es2,
    required this.quantity,
    required this.indexNo,
    required this.descriptionGerman,
    required this.desciptonEnglish,
    required this.partWeight,
    required this.assistantPackingMaterial,
    required this.packer,
    required this.hsCode,
    required this.preferentialOrigin,
    required this.createBy,
    required this.createDate,
    required this.filename,
    required this.packingMonth,
    required this.buildingName,
    required this.areaName,
    required this.sectionId,
    required this.sectionCode,
    required this.sectionName,
    required this.idLocationRack,
    required this.area,
    required this.codeRack,
    required this.rackName,
    required this.unpackBy,
    required this.unpackDate,
  });

  factory DataEntity.fromJson(Map<String, dynamic> json) => DataEntity(
        id: json["Id"],
        containerType: json["ContainerType"],
        idCompany: json["IdCompany"],
        shipName: json["ShipName"],
        shipDeparture: json["ShipDeparture"],
        containerNumber: json["ContainerNumber"],
        fzNumberComplete: json["FzNumberComplete"],
        fzNumber: json["FzNumber"],
        consigneeName: json["ConsigneeName"],
        size: json["Size"],
        summaryPallet: json["SummaryPallet"],
        voyageNumber: json["VoyageNumber"],
        country: json["Country"],
        architecture: json["Architecture"],
        taraWeight: json["TaraWeight"],
        sealNumber: json["SealNumber"],
        consigneeNumber: json["ConsigneeNumber"],
        packageId: json["PackageId"],
        fzNoVolume: json["FzNoVolume"],
        fzSummaryVolume: json["FzSummaryVolume"],
        packageWeight: json["PackageWeight"],
        summaryPalettWeight: json["SummaryPalettWeight"],
        quantityFz: json["QuantityFz"],
        quantityPalett: json["QuantityPalett"],
        quantityFzPalett: json["QuantityFzPalett"],
        commissionNumberFrom: json["CommissionNumberFrom"],
        commissionNumberTo: json["CommissionNumberTo"],
        packageDescription1: json["PackageDescription1"],
        modelType: json["ModelType"],
        lot: json["Lot"],
        packageLength: json["PackageLength"],
        packageWidth: json["PackageWidth"],
        packageHeight: json["PackageHeight"],
        paletteFz: json["PaletteFz"],
        packageDescription2: json["PackageDescription2"],
        partNoPrintFormat: json["PartNoPrintFormat"],
        partNoReadFormat: json["PartNoReadFormat"],
        es1: json["Es1"],
        es2: json["Es2"],
        quantity: json["Quantity"],
        indexNo: json["IndexNo"],
        descriptionGerman: json["DescriptionGerman"],
        desciptonEnglish: json["DesciptonEnglish"],
        partWeight: json["PartWeight"],
        assistantPackingMaterial: json["AssistantPackingMaterial"],
        packer: json["Packer"],
        hsCode: json["HsCode"],
        preferentialOrigin: json["PreferentialOrigin"],
        createBy: json["CreateBy"],
        createDate: json["CreateDate"],
        filename: json["Filename"],
        packingMonth: json["PackingMonth"],
        buildingName: json["BuildingName"],
        areaName: json["AreaName"],
        sectionId: json["SectionId"],
        sectionCode: json["SectionCode"],
        sectionName: json["SectionName"],
        idLocationRack: json["IdLocationRack"],
        area: json["Area"],
        codeRack: json["CodeRack"],
        rackName: json["RackName"],
        unpackBy: json["UnpackBy"],
        unpackDate: json["UnpackDate"],
      );
}
